# Generated by Django 5.1.2 on 2024-10-17 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consultorio', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('capacidad_doctores', models.IntegerField()),
                ('horarios', models.TimeField()),
                ('numero_contacto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('consultorio', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('telefono_celular', models.IntegerField()),
                ('correo_electronico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('ITS', models.BooleanField()),
                ('problemas_cardiacos', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('telefono', models.IntegerField()),
                ('correo_electronico', models.IntegerField()),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('contrasenia', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorConsultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.consultorio')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.TextField()),
                ('tratamiento', models.TextField()),
                ('diagnostico', models.TextField()),
                ('notas', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('detalle_cita', models.TextField()),
                ('correo_electronico', models.IntegerField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.consultorio')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.paciente')),
            ],
        ),
    ]
