# Generated by Django 5.1.2 on 2024-10-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_historialclinico_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='correo_electronico',
            field=models.CharField(max_length=100),
        ),
    ]
