# Generated by Django 5.1.2 on 2024-10-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0003_alter_paciente_correo_electronico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
