# Generated by Django 5.1.2 on 2024-10-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0006_remove_doctor_nombre_doctor_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='doctor',
        ),
    ]
